In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
veri=pd.read_csv('veri.csv')

x=veri.drop(['RowNumber','CustomerId','Surname','Exited'],axis=1)
y=veri['Exited'].values
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [25]:
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

x['Geography']=le.fit_transform(x['Geography'])
x['Gender']=le.fit_transform(x['Gender'])

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ohe=ColumnTransformer([("ohe",OneHotEncoder(dtype=float),[1])],remainder='passthrough')

x=ohe.fit_transform(x)
x=x[:,1:]

In [26]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=18)

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [29]:
import keras
from keras.models import Sequential
from keras.layers import Dense

model=Sequential()

In [46]:

model.add(Dense(6, activation='relu',input_dim=11))
model.add(Dense(6, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=50)

pred=model.predict(x_test)

pred=(pred>0.5)

Epoch 1/50
250/250 [==============================] - 7s 4ms/step - loss: 0.5981 - accuracy: 0.7995
Epoch 2/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7995
Epoch 3/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 4/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 5/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 6/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7995
Epoch 7/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 8/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7995
Epoch 9/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 10/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 11/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 12/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7995
Epoch 13/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 14/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 15/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7995
Epoch 16/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 17/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7995
Epoch 18/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 19/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7995
Epoch 20/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7995
Epoch 21/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 22/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7995
Epoch 23/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.7995
Epoch 24/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 25/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7995
Epoch 26/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 27/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.7995
Epoch 28/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 29/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 30/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 31/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 32/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7995
Epoch 33/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 34/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 35/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 36/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 37/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 38/50
250/250 [==============================] - 1s 5ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 39/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 40/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7995
Epoch 41/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 42/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 43/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7995
Epoch 44/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 45/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7995
Epoch 46/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7995
Epoch 47/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7995
Epoch 48/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7995
Epoch 49/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7995
Epoch 50/50
250/250 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7995
63/63 [==============================] - 0s 2ms/step

In [47]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,pred)
cm

array([[1567,    0],
       [ 433,    0]], dtype=int64)